Models/Purchase.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int ID { get; set; }
        public string Purchase_product { get; set; }
        public string Purchase_qnty { get; set; }
        public System.DateTime Purchase_date { get; set; }
    }
}

Controllers/PurchaseController.cs
using InventoryManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventoryManagementSystem.Controllers
{
    public class PurchaseController : Controller
    {
        Inventory_managementEntities1 db = new Inventory_managementEntities1();
        // GET: Purchase
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DisplayPurchase()
        {
            List<Purchase> list = db.Purchases.OrderByDescending(x => x.ID).ToList();
            return View();
        }
        [HttpGet]
        public ActionResult PurchaseProduct()
        {
            List<string> list = db.Products.Select(x => x.Product_name).ToList();
            ViewBag.ProductName = new SelectList(list);
            return View();
        }
        [HttpPost]
        public ActionResult PurchaseProduct(Purchase pur)
        {
            db.Purchases.Add(pur);
            db.SaveChanges();
            return RedirectToAction("DisplayPurchase");

        }
        [HttpPost]
        public ActionResult Delete(int ID, Purchase per)
        {
            Purchase p = db.Purchases.Where(x => x.ID == ID).SingleOrDefault();
            db.Purchases.Remove(p);
            db.SaveChanges();
            return RedirectToAction("DisplayPurchase");
        }
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            Purchase p = db.Purchases.Where(x => x.ID == ID).SingleOrDefault();
            List<string> list = db.Products.Select(x => x.Product_name).ToList();
            ViewBag.ProductName = new SelectList(list);
            return View(p);
        }
        [HttpPost]
        public ActionResult Edit(int ID, Purchase pur)
        {
            Purchase p = db.Purchases.Where(x => x.ID == ID).SingleOrDefault();
            p.Purchase_date = pur.Purchase_date;
            p.Purchase_prod = pur.Purchase_prod;
            p.Purchase_qnty = pur.Purchase_qnty;
            return RedirectToAction("DisplayPurchase");

        }
        [HttpGet]
        public ActionResult Edit(int ID, Purchase pur)


    }
}

Views/Purchase/DisplayPurchase.cshtml
@model IEnumerable<InventoryManagementSystem.Models.Purchase>

<p>
    @Html.ActionLink("Create New", "PurchaseProduct", "Purchase", new {@class = "btn btn-primary"})
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Purchase Product")
        </th>
        <th>
            @Html.DisplayName("Opening Qunatity")
        </th>
        <th>
            @Html.DisplayName("Purchase Date")
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Purchase_product)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Purchase_qnty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Purchase_date)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit","Purchase", new { @class = "btn btn-primary" }, new { id=item.ID }) |
            @Html.ActionLink("Details", "Detail","Pruchase", new { @class = "btn btn-success" }, new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete","Purchase", new { @class = "btn btn-danger" }, new { id=item.ID })
        </td>
    </tr>
}

</table>

Views/Purchase/Edit.cshtml
@model InventoryManagementSystem.Models.Purchase


@using (Html.BeginForm()) { 
@section Scripts {
        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
        <script src="~/Scripts/jquery-ui-1.13.0.min.js"></script>
        <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
        <script type="text/javascript">

            $(document).ready(dunction(){
                $('input[type=datetime]').datepicker ({
                    dateFormat: "dd/mm/yyyy",
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-60:+0",
                });
            });
        </script>
    }

<h4>Purchase Product</h4>
<hr />
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="form-group">
    @Html.Label("Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownListFor(model => model.Purchase_product, ViewBag.ProductName as SelectList, "Select Product", new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Purchase_product, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.Label("Product Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Purchase_qnty, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Purchase_qnty, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.Label("Pruchase Date", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Purchase_date, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Purchase_date, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Update" class="btn btn-primary" />
        @Html.ActionLink("Cancel", "DisplayPurchase", "Purchase", new { }, new { @class = "btn btn-danger" })
    </div>
  </div>
</div>
}

Views/Purchase/PurchaseProduct.cshtml
@model InventoryManagementSystem.Models.Purchase


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    @section Scripts {
        <script src="~/Scripts/jquery-3.4.1.min.js"></script>
        <script src="~/Scripts/jquery-ui-1.13.0.min.js"></script>
        <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet"/>
        <script type="text/javascript">

            $(document).ready(dunction(){
                $('input[type=datetime]').datepicker ({
                    dateFormat: "dd/mm/yyyy",
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-60:+0",
                });
            });
    </script>
    }

    <h4>Purchase Product</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Product Name", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Purchase_product, ViewBag.ProductName as SelectList, "Select Product", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Purchase_product, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Product Quantity", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Purchase_qnty, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Purchase_qnty, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Pruchase Date", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Purchase_date, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Purchase_date, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
            @Html.ActionLink("Cancel", "DisplayPurchase", "Purchase", new { }, new { @class = "btn btn-danger" })
        </div>
    </div>
</div>
}